spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chatroom?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8002

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      example:
        demo: debug

